Fix warnings in vs2022
ut-issl/s2e-core pull request #117
Opened 2022-04-25 15:27 UTC by 200km

## Overview
Fix warnings in vs2022

## Issue
- #87 

## Details
vs2022で出ているwarningsを全て削除した。  
ただし、algorithmのtransformを使っている`IniReader.cpp`で出ているwarningをどう解決すべきかわからず、そこは手をつけれていない。

-> The warning in transform was removed!

##  Validation results
前後でログ出力結果が変わらないことは確認した

## Scope of influence
ユーザーに影響する修正はない

## Supplement
NA

## Note
GNSS関係の部分で結構修正を入れているので、牛くんにもレビューしてもらう

2022-04-25 16:16 UTC, yngyu approved these changes

2022-04-26 05:08 UTC, seki-hiro approved these changes

2022-04-26 08:55 UTC, sksat requested changes

2022-04-26 08:55 UTC, sksat commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
グローバルに`ToLower`というキャストをするためだけの型を作るのはあんまりよくないですね．
誰かの記事を参考にしたとのことですがちょっとバットノウハウ感があります．
まあそもそも`<locale>`の`std::tolower(charT, const locale&)`は返り値が`charT`なのに，
`<cctype>`の`std::locale(int ch)`は`int`を返すのが渋いというのはありますが．
- https://cpprefjp.github.io/reference/locale/tolower.html

じゃあどうしたらいいのかというとcppreference.comに一応の答えがあって，λ式にするとよいです．
https://en.cppreference.com/w/cpp/string/byte/tolower
```suggestion
  std::transform(valstr.begin(), valstr.end(), valstr.begin(),
    [](char c){ return std::tolower(c); }
  );
```

2022-04-26 08:56 UTC, sksat commented on src/Component/AOCS/InitSunSensor.cpp
> +  const char* Section = section_tmp.data();
`std::string::data()`は現在は`std::string::c_str()`と同一のものであり，かつ(C言語互換の)文字列表現を取得する，という意味では後者の方が一般的で名前とも合っているので`.c_str()`にしたいかもです．
https://cpprefjp.github.io/reference/string/basic_string/c_str.html

2022-04-26 09:06 UTC, 200km commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
Thanks! I modified it.

2022-04-26 09:08 UTC, 200km commented on src/Component/AOCS/InitSunSensor.cpp
> +  const char* Section = section_tmp.data();
I fixed it.

2022-04-26 09:18 UTC, 200km commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
The CI result shows that the modification cannot remove the warnings...

2022-04-26 09:26 UTC, sksat commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
あ，これは`return static_cast<char>(std::tolower(c));`すべきか(型推論されて`int`を返してしまっている)

2022-04-26 09:28 UTC, 200km commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
Thank you so much. I will try again.

2022-04-26 09:34 UTC, 200km commented on src/Library/inih/cpp/INIReader.cpp
> +  std::transform(valstr.begin(), valstr.end(), valstr.begin(), ToLower());
The warning was deleted 👍

2022-04-26 09:34 UTC, sksat approved these changes

2022-04-26 09:35 UTC, 200km commented
I confirmed that the all warnings in g++ and VS2022 were deleted.

2022-04-26 09:35 UTC, merged