WIP: Add 64bit build option
ut-issl/s2e-core pull request #140
Opened 2022-05-29 15:11 UTC by 200km

## Overview
Add 64bit build option

## Issue
- #135

## Details
64bit build option is added to the CMake files.

##  Validation results
Confirmed in the local Docker/Ubuntu environment.  
Others will be confirmed in the CI process

## Scope of influence
small

## Supplement
NA

## Note
NA

2022-05-29 17:29 UTC, 200km commented
CI動作のキャッシュが残っているのをどう治すかわからなかったので、強制的に動かしたらとりあえずはCIに通った。キャッシュ確認の部分はもとに戻す。

2022-05-29 17:35 UTC, 200km commented
cache確認の部分、戻すとまただめになるな。。。cacheよくわからないので、@sksatさんにやってもらったほうが良さそう。

2022-05-30 01:50 UTC, sksat requested changes

2022-05-30 01:50 UTC, sksat commented on ExtLibraries/cspice/install_step.cmake
> +message("install cspice/lib to "${CSPICE_LIB_DEST})
```suggestion
message("install cspice/lib to ${CSPICE_LIB_DEST}")
```

2022-05-30 01:58 UTC, sksat commented on CMakeLists.txt
> +  endif()
無駄に肥大化してきたので，`${CSPICE_DIR}/cspice_*/lib`みたいなやつを`CSPICE_LIB_DIR`とかに切り出した方がよさそう

2022-05-30 02:05 UTC, sksat commented
今作業してなさそう & 僕がやった方がよさそうなのでちょっとcommitしちゃいますね

2022-05-30 02:22 UTC, sksat commented
キャッシュの問題は対応しました

2022-05-30 02:23 UTC, sksat commented on .github/workflows/build.yml
> +        build_option: ['BUILD_64BIT=OFF', 'BUILD_64BIT=ON']
[IMO]
`build_option`はちょっと曖昧すぎる気がします
```suggestion
        build_bit: ['BUILD_64BIT=OFF', 'BUILD_64BIT=ON']
```

2022-05-30 02:25 UTC, sksat commented on CMakeLists.txt
> +      PATHS ${CSPICE_DIR}/cspice_unix_64bit/lib)
[IMO]
32,64bitの区別，こんなかんじにやりがちです(これで十分伝わるし短くて済むので)
```suggestion
      PATHS ${CSPICE_DIR}/cspice_unix64/lib)
```

`lib_64bit`とかも`lib64`でいいと思います

2022-05-30 02:25 UTC, sksat commented on CMakeLists.txt
> +  endif()
これもやるだけなんでやっちゃいます

2022-05-30 02:36 UTC, sksat commented on CMakeLists.txt
> +  endif()
こちらも対応

2022-05-30 02:38 UTC, sksat commented
あとWindows(`CMakeSettings.json`)もですかね？

2022-05-30 04:15 UTC, 200km commented
@sksat ありがとうございます！他の微修正などやっておきます。

2022-05-30 08:05 UTC, sksat commented
一旦LinuxのみということであればLGTMですが，どうでしょう？

2022-05-30 08:07 UTC, sksat approved these changes
一旦LinuxのみということでLGTM．PR title/descriptionにも書いてあるとよさそうです．

2022-05-30 11:12 UTC, merged