Plot latest log
ut-issl/s2e-core pull request #174
Opened 2022-07-21 11:36 UTC by sksat

## Overview
Read latest log if not specify log file and plot.

## Issue
- N/A

## Details
Write in detail.

##  Validation results
Link to tests or validation results.

## Scope of influence
eg. The behavior of XX will be change.

## Supplement
Write additional comments if you need.

## Note
- If there are related Projects, tie them together.
- Assignees should be set if possible.
- Reviewers should be set if possible.
- Set `priority` label if possible.

2022-07-21 13:07 UTC, 200km reviewed
むっちゃ便利な機能の追加ありがとうございます！  
一つお願いなのですが、最新のログを取ってくる機能はこの先他のplot用スクリプトでもかならず使う機能だと思っているので、関数化してもらえると便利だなと思いました。お願いしても良いでしょうか。

2022-07-21 22:00 UTC, sksat commented
了解です！(僕もこれ何度も書くのは違うなと思っていたので)

2022-07-22 07:43 UTC, 200km requested changes
ひとつ前のレビュー漏れなのですが、gs_lonとgs_latのデフォルト値の値が逆転しており、デフォルトでは地上局が表示されなくなってしまっています。値の修正だけお願いします。

2022-07-25 00:09 UTC, sksat commented
おっと．了解です．

2022-07-25 05:35 UTC, 200km approved these changes
修正ありがとうございます。

2022-07-25 05:42 UTC, merged