Merge develop into main for v5.1.0 release
ut-issl/s2e-core pull request #235
Opened 2022-11-22 08:21 UTC by 200km

## Overview
Merge develop into main for v5.1.0 release

## Issue
NA

## Details
I'd like to release v5.1.0 before the large update mentioned in the following issues
#222 - #226 

This minor version update includes modification of several interfaces of public functions. However, they don't affect to user side interface when they follow the nominal usage of S2E written in the tutorial documents. So, I chose minor update instead of the major update.

## Validation results
NA

## Scope of influence
NA

## Supplement
NA

## Note
NA

2022-11-22 14:25 UTC, 200km commented
When should we update the `VERSION` in `CMakeList.txt`?

2022-11-24 10:17 UTC, 200km commented
@sksat こちら、方針としてminorバージョンを上げるということで問題ないでしょうか？問題なければ他のPRがマージされてきたタイミングでこちらも進めようと思います。

2022-11-25 06:49 UTC, sksat commented
はい．その方針で問題無いです．現状どこまでをAPIとして扱うかべきかがだいぶ曖昧なので(強いて言えばSILSでのC2Aとの噛み合わせで，だとしてもbreaking changeではないという認識です)．

2022-11-25 09:34 UTC, 200km commented
ありがとうございます。  
WIP外しましたので、レビューお願いします。

2022-11-25 10:08 UTC, sksat requested changes

2022-11-25 10:08 UTC, sksat commented on CMakeLists.txt
>  # build config
(diff が無くてコメントできないのでここで) `CMakeLists.txt` の `project` の `VERSION` を `5.1.0` にすべきですね

2022-11-25 10:15 UTC, 200km commented on CMakeLists.txt
>  # build config
ありがとうございます。下記の件ですね。
https://github.com/ut-issl/s2e-core/pull/235#issuecomment-1323759293

書き換えておきます。

2022-11-25 10:20 UTC, 200km commented on CMakeLists.txt
>  # build config
https://github.com/ut-issl/s2e-core/pull/246  

こちらで書き換えました。

2022-11-25 13:39 UTC, sksat approved these changes

2022-11-25 13:46 UTC, merged