Feature/add ideal torque generator
ut-issl/s2e-core pull request #306
Opened 2023-02-01 16:44 UTC by kai0722

## Overview
Add ideal torque generator

## Issue
#247 

## Details
Add ideal torque generator with reference  to force generator

##  Validation results
NA

## Scope of influence
The behavior of SampleComponents will change.

## Supplement
NA

## Note
NA

2023-02-01 16:48 UTC, kai0722 commented
TorqueGeneratorのiniファイルに値を設定して実際にシミュレーションを走らせることで動作の確認をしようと思ったのですが，うまくできていません．段階的な現状報告の意味も込めてのプルリクです．

ForceGeneratorの方でもiniファイル変えてシミュレーションしてみたのですが，やはり結果が全く反映されないので，iniファイル以外もいじる必要がありそうなのですが，どこらへんを見ると良さそうですか？

2023-02-01 18:27 UTC, 200km commented
`SampleComponents.cpp`の`// torque generator debug output`の部分のコメントを外して試験していますか？

2023-02-01 18:43 UTC, 200km reviewed
コメントつけました。全てのコメントに返信する必要はないので、気になる部分や議論したいところだけ返信ください。  
まとめて修正後、「修正しました」と書いてもらえると助かります。

2023-02-01 18:43 UTC, 200km commented on data/SampleSat/ini/component/TorqueGenerator.ini
> +torque_magnitude_standard_deviation_N = 0.01
[NITS] 最後に付ける単位は`Nm`でお願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/CMakeLists.txt
> +
[NITS] この改行は必要ないので消してもらえると嬉しいです。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/InitializeTorqueGenerator.cpp
> +  double torque_magnitude_standard_deviation_N = ini_file.ReadDouble(section, "torque_magnitude_standard_deviation_N");
[NITS] ここも単位は`Nm`でお願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/InitializeTorqueGenerator.cpp
> +}
[NITS] 最後に改行をお願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/InitializeTorqueGenerator.hpp
> +TorqueGenerator InitializeTorqueGenerator(ClockGenerator* clock_gen, const std::string file_name, const Dynamics* dynamics);
[NITS] ここも改行をお願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.cpp
> + * @brief Ideal component which can generate for control algorithm test
[NITS] (もしかすると、コピー元も間違っているかもですが) `which can generate torque`が正しそうです。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.cpp
> +TorqueGenerator::TorqueGenerator(const int prescaler, ClockGenerator* clock_gen, const double magnitude_error_standard_deviation_N,
[NITS] 引数名の単位も`Nm`ですね。他にもこのファイル全体で単位の修正お願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.hpp
> + * @brief Ideal component which can generate for control algorithm test
[NITS] cppの方と同じコメント。この下のクラス説明も同様です。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.hpp
> +  inline const Vector<3> GetGeneratedTorque_i_N() const { return generated_torque_i_N_; };
[IMO] forceについては軌道運動に影響するので、慣性座標系、RTN座標系でSetやGetできると便利ですが、torqueについては姿勢運動だけに影響するので、これらの座標系で設定する必要は無いですね。機体固定座標系以外のものは消して良さそうです。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.hpp
> +   * @fn GetGeneratedTorque_b_N
[NITS] このファイルも単位修正お願いします。

2023-02-01 18:43 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.hpp
> +};
[NITS] 改行をお願いします。

2023-02-01 18:43 UTC, 200km commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
> +  // libra::Vector<3> torque_N;
[NITS] ここも単位修正お願いします。

2023-02-02 02:12 UTC, kai0722 commented
修正しました.

`SampleComponents.cpp`の`// torque generator debug output`を外すことで動作の確認もできました！

2023-02-02 08:56 UTC, kai0722 commented
torque値についてはoutputからそのまま図の描画ができた（上部添付図）のですが、軸のずれについては出力されていません。`ForceGenerator`の方も単位がdeg or radで出力されている値が無いため、どこをいじれば軸のずれが出力されるのでしょうか？

取得して反映するまで作る必要がありますか？

2023-02-02 10:30 UTC, 200km requested changes
単位の修正漏れが一つあったので、それを修正していただければapproveしようと思います。

2023-02-02 10:30 UTC, 200km commented on src/Component/IdealComponents/TorqueGenerator.cpp
> +  str_tmp += WriteVector(head + "ordered_torque", "b", "N", 3);
[NITS] ここも `Nm`に修正お願いします！

2023-02-02 10:35 UTC, kai0722 commented
抜けが多くてすみません…修正しました

2023-02-02 10:35 UTC, 200km commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
> +  libra::Vector<3> torque_Nm;
[NITS] 単位修正のときにここのコメントが外れてしまったようなので、コメントつけ直してコミットしてください。この修正でapproveします！

2023-02-02 10:36 UTC, 200km approved these changes

2023-02-02 10:39 UTC, 200km commented
@kai0722 細かくてすみません。コメント `//`のあとにスペースを入れなければいけないルールに引っかかっているようなので、修正をお願いします。

2023-02-02 10:47 UTC, 200km commented
他にも、下記リンクにあるようにフォーマットエラーがでているようです。

https://github.com/ut-issl/s2e-core/actions/runs/4073650114/jobs/7017851577

これらのフォーマットエラーは細かいので手で修正していくのは面倒なのですが、vs codeなどエディタの機能で`clang format`に合わせて自動修正してくれると言うのがあるで、それを使ってみてください。visual studioだと下記などが参考になるかもです。

https://www.linkedin.com/pulse/rough-guide-using-clang-format-visual-studio-c-herbert-marselas

2023-02-02 12:52 UTC, kai0722 commented
こちらでは押せないみたいなので押してください！

2023-02-02 13:25 UTC, merged