Add an interface for HILS testing of I2C components
ut-issl/s2e-core pull request #31
Opened 2022-01-08 07:32 UTC by seki-hiro

## Overview
Add an interface for HILS testing of I2C components.

## Issue
- https://github.com/ut-issl/s2e-core/issues/30

## Details
Add an interface to interact with the simulated component through the com port in order to perform HILS tests of I2C component.

##  Validation results
- ターミナルソフト<->I2C-USB変換機(Master側)<->I2C-USB変換機(Slave側)<->S2Eを接続
   - ターミナルソフトのWriteコマンドで送信されたデータをS2E側で受信できることを確認
   - ターミナルソフトのReadコマンドで，I2C-USB変換機(Slave側)のbufferにS2Eから送信されていたデータをターミナルソフト側で読み取れることを確認
- S2E<->I2C-USB変換機(Master側)<->I2C-USB変換機(Slave側)<->ターミナルソフトを接続
   - 同様にS2Eから送信するWrite/Readコマンドがコムポートを通して正しく送受信されていることを確認

## Scope of influence
模擬I2Cコンポーネントに影響

2022-01-09 00:15 UTC, 200km commented
[Q]このコードを利用するにあたって、ある市販のI2C-USB変換器を使うことを前提にしていると思います。  
それらに関する記述と、それら専用のクラスなどを準備することをイメージしていたのですが、書かれていないようです。  
例えば、SILSのときには純粋にOBC-コンポ間のテレコマ情報のみやり取りされると思うのですが、HILSのときにはそれにI2C-USB変換器向けのヘッダコマンドが追加されたりすると思います。  
そのあたりはどのように扱う予定でしょうか？

2022-01-11 05:50 UTC, seki-hiro commented
> このコードを利用するにあたって、ある市販のI2C-USB変換器を使うことを前提にしていると思います。 それらに関する記述

comポートをループバックしてS2Eのみでやりとりする模擬コンポExpHilsI2cを[push](https://github.com/ut-issl/s2e-core/pull/31/commits/ef46c28556b79508a67a7ca4e7ca1e38cf5ccb8d)しました．UARTの時と同様documentにtutorialを追加して記述したいと思います．

> HILSのときにはそれにI2C-USB変換器向けのヘッダコマンドが追加されたりすると思います。

ヘッダなどはmaster(C2A)から送るコマンドについているという認識です．slave側のI2C-USB変換器がmasterからのコマンドを解釈し，ACKを返す・同期式でmasterとデータを送受信する作業を自動で行ってくれます．  
Slave側のI2C-USB変換器とS2Eの間はテレコマ情報のみでよく，UARTと同様のcomポート操作を通して変換器のRX/TXバッファにアクセスできます．結果として，slave側の模擬コンポにヘッダコマンド等は必要なく，専用のクラスも作っていないという方針です．

2022-01-11 06:35 UTC, 200km commented
> comポートをループバックしてS2Eのみでやりとりする模擬コンポExpHilsI2cをpushしました．

ありがとうございます。確認します。

> ヘッダなどはmaster(C2A)から送るコマンドについているという認識です．

OBC(C2A)から送るコマンドについてはI2C変換器用のヘッダなどはついておらず、純粋なI2Cコマンドが送られると思います。  
HILSとしてS2Eがmaster側をサポートするのであれば、ヘッダ部分を自動でつけてくれたほうが使いやすいと思うのですが、いかがでしょう？ただし、HILSにはmaster側は必須ではない気もするので、優先度は低くて良いかもです。

Slaveの方は特にヘッダなど必要ないものを使っているということで承知しました。
他のSlave側デバイスも全部ヘッダなどが無いのかがわかっていませんが、特定のH/Wを意識して(今回は何もしないということになりますが)ラップするようなことをした方が汎用的かなと思ったりもしたのですが、どうでしょう？

2022-01-11 11:03 UTC, 200km requested changes

2022-01-11 11:03 UTC, 200km commented on src/Component/Abstract/ObcI2cCommunicationBase.cpp
> +  if (sim_mode_ != OBC_COM_UART_MODE::SILS) return;
[MUST] ReadRegisterはHILSのときもSILSのときも同じ動きを取る必要があるように思います。  
あと、`WriteRegister`を実行している`WriteCommand`に相当するHILS用の関数を作る必要がある気がします。  
SILSでは、C2Aが実行したWriteRegisterによってコンポ側のレジスタに値が保存され、コンポ側はそのレジスタから適宜Readをしています。  
今のI2C変換器(Slave側)を使ったHILSでは、C2Aから来たコマンドは変換器内のbufferにはたまりますが、レジスタという感じにはなっていません。なので、定期的にbufferを読んでコンポ(S2E内部)のレジスタにためていくという作業が必要になる気がします。

2022-01-13 03:17 UTC, sksat commented on src/Component/Abstract/ExpHilsI2c.cpp
> +  if (mode_id_ == 0) // master
I2Cの場合master/slaveは規格からある文言なのでそれはそれで混乱を招くのでは，と思いましたが去年10月にRev. 7.0が出てcontroller/targetに改定されているようなので変えるとすればそちらの方がよさそうです．
https://www.nxp.com/docs/en/user-guide/UM10204.pdf

2022-01-13 03:18 UTC, 200km commented on src/Component/Abstract/ExpHilsI2c.cpp
> +  if (mode_id_ == 0) // master
ありがとうございます！　controller/targetでいきましょう。

2022-01-13 03:19 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2c.cpp
> +  if (mode_id_ == 0) // master
ありがとうございます．承知しました．

2022-01-14 02:27 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cCommunicationBase.h
>  class ObcI2cCommunicationBase
ボーレート等の記述を消去しました．
名前も変えてしまった方がわかりやすい気がしたので`ObcI2cTargetCommunicationBase.h`に変更することで対応しました．少しクラス名が長くなってしまった気もしますが問題ないでしょうか？

2022-01-14 02:28 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cCommunicationBase.h
>  };
[ebff310](https://github.com/ut-issl/s2e-core/pull/31/commits/ebff310eb0b6374cf6e7559c381096afe0a71edc)で対応しました．

2022-01-14 02:29 UTC, seki-hiro commented on src/Component/CMakeLists.txt
> + "Abstract/ExpHilsI2c.cpp" "Abstract/ExpHilsI2c.h")
ヘッダの消去と位置の移動を行いました．

2022-01-14 02:29 UTC, seki-hiro commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
> +//#include "../../../Component/Abstract/ExpHils.h"
[ebff310](https://github.com/ut-issl/s2e-core/pull/31/commits/ebff310eb0b6374cf6e7559c381096afe0a71edc)で修正しました．

2022-01-14 02:30 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cCommunicationBase.cpp
> +  if (sim_mode_ != OBC_COM_UART_MODE::SILS) return;
まだ関数の中身は書いてないですが，[7726c1f](https://github.com/ut-issl/s2e-core/pull/31/commits/7726c1fe13cce356f7e08c273eac2c3dde13a8aa)で方針を書きました．
HilsPortManagerでポートの管理を行い，HilsI2cPortでコンポのレジスタを用意します．

Comポートの操作はUARTとほぼ同じです．HilsI2cPortがHilsUartPortクラスを継承することでI2cのTargetコンポもcomポートの送受信が行えると想定していますが，実際の挙動を確認してみます．

2022-01-14 02:31 UTC, seki-hiro commented
> HILSとしてS2Eがmaster側をサポートするのであれば、ヘッダ部分を自動でつけてくれたほうが使いやすいと思うのですが、いかがでしょう？ただし、HILSにはmaster側は必須ではない気もするので、優先度は低くて良いかもです。

S2EのMaster側の使われ方があまり想定できていませんが，ループバック検証には必要なので合わせて実装してしまおうかと思います．

> 特定のH/Wを意識して(今回は何もしないということになりますが)ラップするようなことをした方が汎用的かなと思ったりもしたのですが、どうでしょう？

H/W固有のヘッダー/フッターをどこでラップするのが適切か少し検討してみます．

2022-01-19 09:47 UTC, seki-hiro commented
検証中メモ
- 前提
   - Controller側からのReadコマンドでTarget側変換器bufferのデータが読み出される
- これまでの方針
   - コンポが保持するレジスタアドレス`saved_reg_addr_`に基づいてテレメを常時Target側変換器に送りつけておく
      - 送りつける前に毎回変換器bufferをクリア
   - ControllerからReadコマンドが来たタイミングでテレメが読まれる
- 検証経過
   - USB側からTarget側変換器のbufferをクリアする手段がなさそう
      - I2C側からしかできない
   - Target側変換器のbufferが詰まりS2E（コムポート操作部分）がフリーズ
- 今後の方針案
   - Controllerからのテレメ要求のタイミングに合わせて必要な分だけTargetコンポからテレメを送る
   - USB側からbufferをクリアできる（新しいデータが古いデータを押し出す，など）変換器を見つける

2022-01-26 04:49 UTC, seki-hiro commented
@200km Controller側からのテレメReadコマンドに対して，Target側の変換器が同期的にテレメを返す部分についてご相談です．
現状，模擬コンポの保持するレジスタアドレス(`saved_reg_addr_`)に応じて，模擬コンポからTarget側変換器に定期的にテレメを下ろしていますが，これだとTarget側変換器のbufferが詰まってしまいます．bufferのクリアは，I2Cコマンドでできるようです．
そこで

1. 模擬コンポはTarget側変換器に定期的にテレメを下ろす（bufferが詰まったらwrite timeoutで書き込めなくなる）
2. C2AでTarget側変換器のbufferをクリアする
3. 直後に模擬コンポから変換器に最新のテレメが送られる
4. C2Aでテレメを読み取る

という方法があるかと考えたのですがいかがでしょうか？HILSの場合だけ，テレメを要求する直前に，Target変換器のbufferクリアコマンドを送るように，C2A_USERにも変更が必要になります．

他の方法としては，そもそもVirtual Com Port(VCP) Interfaceを使わずに，D2XX Interfaceを使うものがあるようです．この場合，模擬コンポからTarget側変換器のbufferをクリアしたりできそうです．

2022-01-26 07:38 UTC, seki-hiro commented
ターミナルソフトを用いてTarget側変換器に大量のデータを送ると，512bytes（buffer size）を超えたところでソフトが落ちる．

S2Eを用いてTarget側変換器に大量のデータを送った場合は，buffer sizeを超えると書き込みタイムアウトとなって続行する．ただし，そのままだとポートを閉じるときにデバッグがフリーズする．

@200km 結局，bufferをクリアしないまま変換器にデータを送り続けるのは挙動が不安定になりそうです．D2XX Interfaceの方で実装できるか試してみます．

2022-02-01 13:44 UTC, sksat commented
こちらconflict発生してしまっているのでrebase&修正お願いします(`#include "../../../hoge.h"`みたいなやつをやめた，というやつです: #49)

2022-02-28 05:21 UTC, seki-hiro commented
@200km 
遅くなってすみません．検証を進めた結果，Target変換器のlatencyが律速となり，テレメ要求に対して即座にテレメを返答することができないということがわかりました．

<img width="1081" alt="verification" src="https://user-images.githubusercontent.com/82629762/155926835-57e0e9e8-55f7-4bfa-b52c-c3ecff20a8e2.png">

Target側の変換器は，I2Cで来たテレメ要求コマンドをrx bufferに格納し，latency time経過後，bufferに溜まったデータをUART側に送信します．このlatency timeは最小でも1msであり，その間にController側からI2C Readが行われてしまいます．結果，Target変換器のtx bufferにテレメが用意できる前に，Target変換器に対してI2C Readが行われ，読み取るデータがないと判断されてしまいます．

そこで，Target変換器にあらかじめ数フレーム分のテレメトリを溜めておく方針で実装を進めたいと思います．

補足
・変換器を変えたとしても，Target側変換器において，latencyが最小で1msかかってしまうことに変わりはない．
・baudrateが小さい場合（9600以下程度）はI2C Readの送信に時間がかかり，その間にテレメ送信が完了することもある（テレメ要求に合わせてテレメ返答することに成功する場合がある）．
（・latency timeを変える方法として，データシートにはD2xx Interfaceを用いる方法しか載っていないが，デバイスマネージャーから変更することができた．）

2022-03-02 23:40 UTC, seki-hiro commented
検証結果をdocumentにまとめました。https://github.com/ut-issl/s2e-documents/pull/18
レビューお願いします。

2022-03-07 09:32 UTC, 200km commented
@seki-hiro こちら、一度ミーティングで詳細確認させてください。

2022-03-07 12:15 UTC, 200km requested changes
コメントつけました。詳細はミーティングしながら詰めていきましょう。

2022-03-07 12:15 UTC, 200km commented on src/Interface/HilsInOut/HilsPortManager.h
> +  #include "Ports/HilsI2cTargetPort.h"
[IMO] このHilsPortManagerの方針の確認ですが、ここにI2Cなども全部書いていくのか少しミーティングで相談させてください。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.cpp
> +#include <iostream>
はい、そうです。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +  // unsigned char i2c_address_;
現状使っていないので削除します。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +  int sils_port_id_;
すみません。残ってしまっていましたが、SILSポートIDは使っていないですね。下に

> このクラスは元々やりたいHILS(PC-OBC間通信)だけ考えると必要ないという感じ

とあるように、HILSの検証とtutorialのためだけに作っているクラスなので、SILSに対応させる必要は現状なさそうです。そのため、` int sils_port_id_;`はひとまず削除したいと思います。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +#include "../CDH/OBC.h"
削除します。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +class ObcI2cControllerCommunicationBase
Targetコンポの検証を行うために作られたControllerのクラスという存在意図を追記したいと思います。

関連して、ObcI2cControllerCommunicationBaseという命名がおかしい気がしてきました。I2cControllerはI2cTargetと通信するので、単純に繋げるとI2cControllerI2cTargetCommunicationBaseとなります。しかしこれだと、ControllerとTargetのどちらかわからない&長いので、I2cControllerCommunicationBaseがいいかと思ったのですがいかがでしょうか？

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +    HilsPortManager* hils_port_manager
> デバイスによっては初期化時に設定できたりするのかもしれない

この可能性はありそうです。I2Cアドレスの設定方法はH/Wに依存するため、I2Cアドレスは既定であるとしてここでは実装しています。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +  int sils_port_id_;
`unsigned`にしました

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
> +ObcI2cTargetCommunicationBase::ObcI2cTargetCommunicationBase(int sils_port_id, const unsigned char i2c_address, OBC* obc)
`const unsigned int`で統一しました

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
> +  else // sim_mode_ == OBC_COM_UART_MODE::HILS
switch文にしました。もし問題なければ、PR外ですが、`ObcCommunicationBase.cpp`内でも修正しようと思います。よろしいでしょうか？

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.h
> +//   Supposed to be used in connection with I2C-USB Controller converter
追記しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.h
> +// emulated components for training
ありがとうございます。修正しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.h
> +  static const uint8_t kHeader_ = 0x53; // S
提案いただいた方がわかりやすいので、修正しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.cpp
> +  const unsigned char req_tlm_cmd_size = 5;
修正しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.cpp
> +  receive_cmd[2] = (char)kTlmSize; // bytes to read
そうですね、修正しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.cpp
> +  const unsigned char receive_cmd_size = 4;
修正しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.cpp
> +  std::cout << "Controller requests Telemetry" << std::endl;
追記しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cTarget.h
> +// emulated components for training
同様の修正を加えました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cTarget.h
> +  unsigned char i2c_address_;
すみません、必要ないものが残ってしまっていたようです。消去しました。

2022-03-14 06:05 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cTarget.cpp
> +  int add_frame_counter = kStoredFrameSize - GetStoredFrameCounter();
Target変換器に追加すべきフレーム数を表しています。他には、`additional_frame_num`、`replenishment_frame_number`、`num_of_additional_frame`などがあるかと考えましたが、ひとまず`additional_frame_num`に変更しています。

2022-03-14 06:05 UTC, seki-hiro commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
> +  //exp_hils_responder_ = new ExpHils(clock_gen, 1, obc_, 3, 9600, hils_port_manager_, 1);
UART通信のループバック検証を行うコードをコメントアウトしています。
UARTの方を削除するのであれば、I2Cの方も削除してしまって、documentのtutorialにUART/I2Cそれぞれの場合のsample codeをアップロードする方が良さそうでしょうか？
その場合、s2e-coreの`SampleComponents.cpp`から、HILSに関連する記述が全て削除されるかと思います。

2022-03-14 06:05 UTC, seki-hiro commented on src/Interface/HilsInOut/Ports/HilsI2cTargetPort.h
> +// The emulated component transmits to and receives from the converter via the com port.
修正しました。

2022-03-14 06:06 UTC, seki-hiro commented on src/Component/Abstract/ExpHilsI2cController.cpp
> +  : ComponentBase(30, clock_gen),
コンストラクタを修正しました。

2022-03-14 06:13 UTC, 200km commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +class ObcI2cControllerCommunicationBase
確かにOBCはなくても良い気もします。Communicationも必要ない気もします。

2022-03-14 07:08 UTC, seki-hiro commented on src/Interface/HilsInOut/HilsPortManager.h
> +  #include "Ports/HilsI2cTargetPort.h"
I2CのコンポもCOM portと変換器の間はUART通信を行っており、COM port操作のために同じ関数を使っているため、一つのファイルにまとめたままにしておく。

2022-03-14 07:42 UTC, 200km commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +    HilsPortManager* hils_port_manager
ミーティングの結果、IFとしてI2Cアドレスを入れることに決めた。

2022-03-14 07:42 UTC, 200km commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
> +  else // sim_mode_ == OBC_COM_UART_MODE::HILS
はい。合わせて修正してください。

2022-03-14 07:46 UTC, 200km commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
> +  //exp_hils_responder_ = new ExpHils(clock_gen, 1, obc_, 3, 9600, hils_port_manager_, 1);
意図理解しました。UART試験用のものとI2C試験用のものが同じ変数名で定義されているのは分かりづらい+同時に試験できないということになるので、命名にi2cなどを入れたりしてわかりやすくすると良いと思います。

あと、コメントアウトで試験するかどうかを選んでいると思いますが、そのあたりの説明を書き加えてもらえるとよりわかりやすいかなと思います。

2022-03-14 07:47 UTC, 200km commented on src/Interface/HilsInOut/HilsPortManager.h
> +  #include "Ports/HilsI2cTargetPort.h"
ミーティングで話し合い、I2Cもここに書くこととした。

2022-03-14 08:13 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cControllerCommunicationBase.h
> +class ObcI2cControllerCommunicationBase
OBCを削除しました。通信用のクラスということでCommunicationは残しています。

2022-03-14 08:13 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +    HilsPortManager* hils_port_manager
I2Cアドレスを初期化する場合に備えて、HILS用のコンストラクタにも`i2c_address`を加えておきました。

2022-03-14 08:13 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
> +  else // sim_mode_ == OBC_COM_UART_MODE::HILS
修正しました。

2022-03-14 08:13 UTC, seki-hiro commented on src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
> +  //exp_hils_responder_ = new ExpHils(clock_gen, 1, obc_, 3, 9600, hils_port_manager_, 1);
修正しました。
一通り修正を終えました。

2022-03-14 09:02 UTC, 200km approved these changes
小さな修正コメントだけなのでapproveしています。微修正後マージしてください。

2022-03-14 09:02 UTC, 200km commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +    HilsPortManager* hils_port_manager
[NITS] 細かいですが、SILS専用コンストラクタと引数の順序が一致していたほうがわかりやすい気がしました。SILS/HILS兼用コンストラクタもいい感じに順序変えても良いと思います。

2022-03-14 10:02 UTC, seki-hiro commented on src/Component/Abstract/I2cControllerCommunicationBase.h
> +// This class simulates communication between the I2C Controller and the I2C Target.
修正しました。

2022-03-14 10:02 UTC, seki-hiro commented on src/Component/Abstract/ObcI2cTargetCommunicationBase.h
> +    HilsPortManager* hils_port_manager
兼用コンストラクタ含め、順序を一致させました。

2022-03-14 10:04 UTC, seki-hiro commented on src/Component/Abstract/ObcCommunicationBase.cpp
> +    break;
errorメッセージを追加しました。

2022-03-14 10:08 UTC, seki-hiro commented
微修正完了したのでマージします！

2022-03-14 10:09 UTC, merged