Update link margin analysis
ut-issl/s2e-core pull request #364
Opened 2023-03-15 04:25 UTC by TomokiMochizuki

## Overview
Update link margin analysis

## Details
- update functions related to link margin analysis to simulate uplink margin analysis and downlink margin analysis simultaneously.

##  Validation results
Link to tests or validation results.
![test_s-band](https://user-images.githubusercontent.com/56018919/225205826-76a0cb02-620b-473d-b6be-41c87a9632e3.png)

## Scope of influence
eg. The behavior of XX will be change.

## Supplement
Write additional comments if you need.

## Note
- If there are related Projects, tie them together.
- Assignees should be set if possible.
- Reviewers should be set if possible.
- Set `priority` label if possible.

2023-03-15 05:23 UTC, 200km commented
@TomokiMochizuki こちら、major updateに当たると思いますので、https://github.com/ut-issl/s2e-core/pull/303 をベースに開発しPRもそちらに対して出してもらえると助かります。

2023-03-15 05:39 UTC, TomokiMochizuki commented
> @TomokiMochizuki こちら、major updateに当たると思いますので、#303 をベースに開発しPRもそちらに対して出してもらえると助かります。

わかりました！

2023-03-15 15:18 UTC, TomokiMochizuki commented
@200km 
v6.0.0に変更したのですが，is_visible_flagが正常に機能していない気がしているのですが，こちら気のせいでしょうか...？

2023-03-15 15:19 UTC, TomokiMochizuki commented
同じシミュレーション条件でflagが立たなくなっている気がします．

2023-03-15 15:26 UTC, TomokiMochizuki commented
> 同じシミュレーション条件でflagが立たなくなっている気がします．

こちら再度確認してからまた連絡します．

2023-03-15 16:00 UTC, TomokiMochizuki commented
> 

この問題は解決しました．
propagete_modeが単純に違っただけでした．

2023-03-16 02:30 UTC, TomokiMochizuki commented
@200km 
こちら，検証含めて確認が終わりましたのでreviewの程お願いします．

2023-03-16 06:13 UTC, 200km requested changes

2023-03-16 06:13 UTC, 200km commented on src/components/real/communication/antenna.cpp
> +  if (gain_model_name == "ISOTROPIC") {
[NITS]古い表記に戻ってしまっているようですので、`kIsotropic"`などに戻してください。

2023-03-16 06:13 UTC, 200km commented on src/components/real/communication/antenna.hpp
> +  inline double GetBitrate() const { return tx_bitrate_bps_; }
[IMO] `GetTxBitrate_bps`にしてもらえると命名規則と一致します。

2023-03-16 06:13 UTC, 200km commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
[Q] txやrxなどを取り除いた意図は何でしょうか？これらの表記があったほうがより明確になる気がします。

2023-03-16 06:13 UTC, 200km commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
[Q] bitrateはアンテナが決めるものではなく、その前段の送信機などで決めるものな気もするのですが、ここにこのパラメータを置くべきなのでしょうか？

2023-03-16 06:41 UTC, 200km requested changes

2023-03-16 06:41 UTC, 200km commented on src/components/real/communication/ground_station_calculator.cpp
> +    double testA = ground_station_antenna.CalcTxEirp_dBW(theta_on_gs_antenna_rad, phi_on_gs_antenna_rad);
[NITS] warningsがでていると思うので、修正をお願いします。

https://github.com/ut-issl/s2e-core/actions/runs/4432681822/jobs/7776978157#step:10:149

2023-03-16 07:06 UTC, TomokiMochizuki commented on src/components/real/communication/antenna.cpp
> +  if (gain_model_name == "ISOTROPIC") {
修正しました

2023-03-16 07:08 UTC, TomokiMochizuki commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
衛星側Tx - 地上局側Rx
衛星側Rx - 地上局側Tx
の両者のパターンを同じ関数で処理したかったためです．

2023-03-16 07:12 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
送信機などで決めるのであれば，`tx_output_W`や`frequency_MHz`もな気がしていて．どちらかに統一したかったです．

2023-03-16 07:13 UTC, TomokiMochizuki commented on src/components/real/communication/ground_station_calculator.cpp
> +    double testA = ground_station_antenna.CalcTxEirp_dBW(theta_on_gs_antenna_rad, phi_on_gs_antenna_rad);
修正しました．

2023-03-16 07:15 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +rx_antenna_gain_model = kIsotropic
> [NITS]古い表記に戻ってしまっているようですので、kIsotropic"などに戻してください。

この影響で*.iniファイルを修正しました．

2023-03-16 07:29 UTC, 200km commented on src/components/real/communication/antenna.cpp
> +  if (gain_model_name == "ISOTROPIC") {
あ、すみません。  
ここはiniとのI/Fの部分だったんですね。その場合は`ISOTROPIC`で正しかったです。

2023-03-16 07:31 UTC, 200km commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
`frequency_MHz`はアンテナも関わってくる気がするので、ここで良いのではないでしょうか？  
`tx_output_W`はたしかにそうなので、送信機側に動かしても良いと思います。

2023-03-16 07:34 UTC, 200km commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
その場合、どこか別の場所で、この関数が引数を変えて複数回呼ばれるということになるのだと思います。  
そうなると`Update`という関数名では不適切な気がします。

2023-03-16 08:36 UTC, TomokiMochizuki commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
```c
components_->GetGsCalculatorSdown()->Update(spacecraft, spacecraft.GetInstalledComponents().GetAntennaSdown(), *this, *(components_->GetAntennaSdown()));
  components_->GetGsCalculatorSup()->Update(spacecraft, spacecraft.GetInstalledComponents().GetAntennaSup(), *this, *(components_->GetAntennaSup()));
```
みたいにgs_calculator自体も結局TxとRXで別々に作成することになるので関数が引数を変えて複数回呼ばれるという形ではない気がします．

2023-03-16 10:13 UTC, 200km commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
元々は,`GsCalculator`は`衛星側Tx -> 地上局側Rx`を前提にして作られていた、それを今後は`衛星側Rx <- 地上局側Tx`もやっていきたい　という大前提がある感じでしょうか？  

`GsCalculator`がそもそもどんな立ち位置で存在すべきなのかという問題になりますね。下記issueなどとも関連しそうです。

https://github.com/ut-issl/s2e-core/issues/315

現時点では、`衛星側Tx -> 地上局側Rx`でしか使っていない気がするので、この修正は上の議論と合わせて別議論でもよいのではないでしょうか？

2023-03-16 15:36 UTC, TomokiMochizuki commented on src/components/real/communication/ground_station_calculator.cpp
> +void GroundStationCalculator::Update(const Spacecraft& spacecraft, const Antenna& spacecraft_antenna, const GroundStation& ground_station,
なるほどです．
そうしましたら，とりあえずはPR#315で行うということでいいと思います．

2023-03-16 15:50 UTC, TomokiMochizuki commented on src/components/real/communication/antenna.cpp
> +  if (gain_model_name == "ISOTROPIC") {
了解です．しゅうせいしました　．

2023-03-16 16:03 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
> `frequency_MHz`はアンテナも関わってくる気がするので、ここで良いのではないでしょうか？ `tx_output_W`はたしかにそうなので、送信機側に動かしても良いと思います。

それを行いますと，
```c
tx_eirp_dBW_ = 10 * log10(tx_output_power_W_) + tx_parameters_.loss_feeder_dB_ + tx_parameters_.loss_pointing_dB_;
```
の箇所がうまくいかなくなってしまうので，tx_eirp_dBWを別の場所に移行しなければならないので，アンテナの方に押し込んだほうがいいと思います．

2023-03-20 02:52 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
> - 現時点ではAntenna クラスにSetTxBitrateやSetTxPowerなどの関数を準備して、これらの値を別の通信システムから設定できるようにしておく
> - 理想的な状態への改修に向けてTODOやFIXMEでコメントつけておく、issueも立てる

これに関してですが，現状送受信機のClassが存在していないので，とりあえずアンテナに帰属させるのがいいと思ったので，そのままにしています．GroundStationCalculatorにあるのも変なので．
そのうえで，FIXMEを切っておきました。

2023-03-20 02:59 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
- issueに関しては #366 で切っておきました．

2023-03-20 07:05 UTC, 200km commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
Set関数を準備するというのは、「そのパラメータはひとまずアンテナに帰属するが、別のコンポが制御できるような余地を残しておく」という意図です。
Set関数を使わなかった時に使われるパラメータ初期値は今のような設定で良いので、動作としては今と特に変わらないかなと思います。

2023-03-21 02:41 UTC, TomokiMochizuki commented on data/sample/initialize_files/components/ground_station_antenna.ini
> +tx_bitrate_bps = 10000
ありがとうございます。
では、マージします

2023-03-21 02:41 UTC, merged