Reduce dependency to C2A
ut-issl/s2e-core pull request #38
Opened 2022-01-23 11:11 UTC by meltingrabbit

## Overview
C2Aとの依存性を低減させる

## Issue
NA

## Details
C2Aの内部パスや内部関数をこちらで持つのは，依存性を高めてしまい，C2A側の更新に弱くなってしまうので，多少低減させた．

##  Validation results
ISSL内部のOBCのSILS環境でビルドできることを確認

## Scope of influence
NA

## Supplement
NA

2022-01-23 12:53 UTC, 200km requested changes
コメントを英語にしてもらえると助かります。

2022-01-23 13:28 UTC, meltingrabbit commented
すみません，直しました．

今（当面）の方針は，
「PRのディスクリプションのみ英語で，その他の議論は英日どちらでも可」でよろしいでしょうか？

2022-01-23 14:43 UTC, 200km commented
あ、すみません。コード内のコメント(例えば`AM_initialize_all_apps での時間計測のためにここで初期化`など)を英語にしたいということでした。  
PRのディスクリプションや議論などはできるだけ英語ですが、議論がスムーズに進むこと優先ということで、日本語でも良いです。

2022-01-23 15:04 UTC, meltingrabbit commented
そちらでしたか，すみません．直します．

2022-01-24 04:30 UTC, 200km approved these changes
手元で動作確認もできたので問題ありません。

2022-01-24 04:42 UTC, meltingrabbit commented
レビューありがとうございます．ではマージします．

2022-01-24 04:42 UTC, merged