WIP: Implementation test for new ODE solver
ut-issl/s2e-core pull request #415
Opened 2023-05-23 14:39 UTC by 200km

## Overview
Implementation test for new ODE solver

## Issue
- NA

## Details
Implementation test for new ODE solver.

##  Validation results
See GoogleTest results.

## Scope of influence
Not used in the S2E's execution. Test code only.

## Supplement
NA

## Note
NA

2023-05-23 18:30 UTC, 200km commented
RK4だけでなくより高次のRKを実装できるよう、今のODEを参考にしつつ、作ってみました。  
- RungeKuttaベースクラス
  - RungeKuttaベースを継承して係数値を定義したクラス(RungeKuttaXクラスとする)
    - RungeKuttaXクラスを継承し、具体的な微分方程式を定義したクラス(例えば軌道計算のRK4など)
のような構成になっています。

ただ、これだと
- 軌道計算のRK4
- 軌道計算のRK5
などを作る必要があり、`軌道計算の微分方程式`という共通部分を活かせませんし、積分方式だけRK4からRKF5に変えるなどもやりづらいかなと思っており、少し改善したいと思っています。

2023-05-26 11:39 UTC, 200km commented
実現したいことは、次の通り
- 運動方程式を定義する`DerivativeFunction`を一度だけ定義すれば良くしたい
- どの数値積分手法(RK4なのか、RKXなのか)で解くかは自由に選べるようにしたい

アプローチは次のようなものが考えられそう
1. `軌道計算のRK4`, `軌道計算のRK5`などのクラスたくさん作り、`軌道計算`の中でどれを実体化し、コールするかを選ぶ
  - 軌道計算の部分はinterface等で一度実装すれば良いようにする
  - 気になる点:　クラスがたくさん作られ事になってめんどくさそう？
2. `NumricalIntegration`のクラスを作り、その実体化のときにどのRKを使うかを決める。`軌道計算`クラスは`NumricalIntegration`クラスを継承し、その中で`DerivativeFunction`を定義する
  - 気になる点:　 `NumricalIntegration`が運動方程式と数値積分手法をつなぐハブになり、このクラスの修正が全てに影響を与えることになってしまう。

上のアプローチに付いてのコメントや、その他の提案があればぜひ教えてください。

2023-05-26 18:35 UTC, 200km commented
とりあえず、`運動方程式を定義するDerivativeFunctionを一度だけ定義すれば良くしたい`をできるように修正した。

2023-05-29 20:23 UTC, 200km commented
実装方針これで良いと思って来たのでWIPを外しました。  
最終的な構成は次のようなものです。
- InterfaceOde: 常微分方程式定義用のインターフェースクラス
  - これを継承した各クラスをユーザーが作り、NumericalIntegratorと合わせて利用する
- NumericalIntegrator: 最上位のAbstractクラス
  - RungeKutta: 一般的なRungeKutta法全ての基底クラス (このまま使うことはない)
    - RungeKutta4: RK4用パラメータを設定したクラス　(このまま使える)
    - EmbeddedRungeKutta: Embedded法用の基底クラス (このまま使うことはない)
      - RungeKuttaFehlberg: RKF用パラメータを設定したクラス(このまま使える)
  - MultiStep: まだ実装していないが、今度RK以外の数値積分手法も実装していく想定
- NumericalIntegratorManager: ユーザーが自由に数値積分手法を選べるようにRK4, RKFなどを割り当てるやつ
  - これとiniファイルを組み合わせて、`軌道計算をRK4でやるかRKFでやるか選択できるようにする`という機能を実現する

- テスト用コード
  - ode_example: InterfaceOde用サンプル
  - test_runge_kutta: テスト用コード
    - RK4とRKFの精度比較などもここで行っている

2023-06-01 08:11 UTC, sksat requested changes

2023-06-01 08:11 UTC, sksat commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
ファイル名の `_template` suffix は命名と実態がズレているように思います．`EmbeddedRungeKutta` はクラスの時点で template class なので，「template でないモノ」と「template なモノ」という分割ではないですし．

2023-06-01 11:08 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
わかりました。今までは、`libra`は`math`として使われていましたが、実際は`libra::math`がよいし、そう考えるとここは`libra::numerical_integration`が良いということですよね。  

libraryディレクトリ以下は同様に`libra::orbit`等で名前空間を切っていく方針が良さそうでしょうか？そうであれば、そのようなissueを切っておこうと思います。

2023-06-01 11:13 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
`_template`は昔の`vector_template.hpp`などを踏襲して付けたもので、おそらく前の命名の意味は、`template関数の実装部分`という意味でつけられていたのだと思います。(前の命名についてあまり意図を理解できていませんが、本当は`vector.cpp`としたいところだけれど、.hppにする必要があり、名前を変えるために`_template`をつけたと想像しています)

今は、`vector_template_function.hpp`のような感じで統一されていますね。  

何れにせよ、`_template`をつけるよりも良い命名があればそれにしたいとは思います。何か良い案はありますか？

2023-06-01 11:14 UTC, 200km commented on src/library/numerical_integration/numerical_integrator_manager.hpp
> +  NumericalIntegrator<N>* integrator_;
ありがとうございます。他のコードも含めて、今後は`スマートポインタを使うように寄せる`方針で進めようと思います。

2023-06-02 13:47 UTC, sksat commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
そもそも `library` ないし `libra` というリリース単位（ここでは library 以外の S2E のコードに対して機能を提供するという意味でリリースという言葉を使っています）にあまり必然性がなく不自然なので，`src/` 直下に `numerical_integration` のようなディレクトリ/名前空間を直接切っていく方がよいのではないでしょうか？（それでいうと，既存の `library` も `libmath` みたいな実際の役割に対して適切な名前を付け直してあげた方がよいかもしれません．breaking change になるので後回しでよいとは思いますが）

2023-06-02 13:52 UTC, sksat commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
「あまり S2E の文脈に限ったものではなく，汎用的に使い回せるもの」みたいな意味で library と呼ぶこと/区別するためにディレクトリを切ること自体はよいとは思うのですが，それらをひとまとめにして「s2e-core の library」みたいな単位で使ったり呼びたくない/呼ぶべきではない（ライブラリであることしか分からないので），というモチベーションです．

2023-06-02 14:06 UTC, sksat commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
`vector_template.hpp` の時はまず全体の行数が長かったので分割したかったので，クラスの宣言と（template な）実装という単位で分割し，そのために後者に`_impl` のような suffix を付けて区別するとよいのではないか，と提案したものの，`impl` という略語は S2E の文脈では一般的ではないし，これは実態としては template なモノかどうかでの区別なので，`_template` で，となったと記憶してます．

それも踏まえると，今回の場合はどちらも50行程度ですし，そもそもファイル分割せずヘッダを1つにまとめてもよいように思います．

2023-06-02 17:57 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
> src/ 直下に numerical_integration のようなディレクトリ/名前空間を直接切っていく方がよい

ちょっとこのPRでやりたいと想定していたこととぜんぜん違うことを議論されようとしている気がしています。今この段階でlibraryはそのまま`src/numerical_integration`はS2Eのこれまでの方針から変わりすぎるので、やりたくはないです。

`library`を`libramath`(S2Eの命名規則的には、`library_math`)にするかと合わせて、別で議論させてください。

2023-06-02 17:57 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
ここでは、今のディレクトリ構成のまま`libra::numerical_integration`とだけしておきます。

2023-06-02 18:11 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
`まず全体の行数が長かったので分割したかった`のではなく、そもそもS2Eの元となったシミュレータの時点で、宣言と実装を分けるために、`_tfs`や`_ifs`等が付けられて別れていたという状況だと思います。(昔過ぎて意図はもうわからないので`想像しています`と書いています。)

例えば、`Vector.cpp`, `Vector.hpp`, `Vector_ifs.cpp`, `Vector_tfs.cpp`の4つがあったような状況で、v6.0.0で、`Vector.cpp`と`Vector_ifs.cpp`が統合され、名前も変えて、
- `vector.hpp`: クラスの宣言
- `vector.cpp`: template以外の実装 (3次元で限定されているもの)
- `vector_template_functions.hpp`: templateの実装

という感じに分かれています。

なので、今の命名は`_template(_functions)`は`templateの実装`を指す形だということにはなっているかと思います。  
今回のものを`宣言と実装を分けずに全て1ファイルに書く`事自体は悪くないなとは思いつつ、`宣言と実装を分けたほうが読みやすいのでは`と思うところもあり、決めるの難しいなと思っています。

今回も[runge_kutta_4.hpp](src/library/numerical_integration/runge_kutta_4.hpp)などはこの中で実装をしてしまっていますが、これはRK4のパラメータを代入しているだけというのが逆にわかりやすいので、ありかなとは思っています。  
逆に[runge_kutta_fehlberg.hpp](src/library/numerical_integration/runge_kutta_fehlberg.hpp)は`runge_kutta_4.hpp`にあわせるために1ファイルにしてしまいましたが、パラメータ代入だけでなく、RKF特有の実装も入ってしまっているので、本当は`runge_kutta_fehlberg_hoge.hpp`のような形で分けたほうが良いのでは？と思ったりもしています。

2023-06-02 18:27 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
なので、次のことを決めて進めると今後の見通しも含めてスッキリするなと思っています。
- `宣言`と`実装`は分けたほうが良いのか、1ファイルが短くなるなら今後他のものもまとめていく方針が良いのか？
  - template.hppに限らず、cppの場合も？
- 1ファイルが長くなる場合等でファイルを分割する場合、現状の`_template_functions.hpp`的なものを作らなければならなくなってしまうが、どんな命名にするのが良さそうか。


僕の現状の意見としては、
- `宣言`と`実装`は分ける方針がよく、ファイルの長さではなく「基本は分けるが、わけないほうが見やすい場合のみ統合する」くらいが良いと思っている
  - これに従うと、`runge_kutta_fehlberg.hpp`は分けたほうが良さそう
- `template関数の実装部分`という意味で、`_template_implementation.hpp`が良さそう

という感じです。

2023-06-02 18:41 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
issueは切っておきました。  
https://github.com/ut-issl/s2e-core/issues/423

2023-06-05 07:23 UTC, 200km commented on src/library/numerical_integration/numerical_integrator_manager.hpp
> +  NumericalIntegrator<N>* integrator_;
done

2023-06-05 07:23 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +namespace libra {
done

2023-06-06 12:04 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
ありがとうございます。  
- 宣言と実装は分けた方が良い
- 必ずしもファイルで分ける必要はない（例えばinline関数や今回の場合のRK4の係数定義などは、実際ヘッダファイルに書いていますし、それが良いと思っています）

の考えは同じだと思っています。  
後はどのような基準でファイルを分けるのかというグラデーションの問題なのかなと思います。  
改めて基準を考えると、僕の中では`処理内容の違いに対する頭の切り替え`が重要な気がしています。
- ただ値を代入するだけならヘッダ内にあっても読みやすさは変わらない
  - GetterやSetterなどのinline関数
  - RK4のパラメータ設定
- （複雑な）数式やif文が入ってくると、別ファイルにあってくれた方が頭が切り替えやすい（IF確認するだけの頭と実装の中身を深く見ようとする頭）

というのが僕の今持っている感覚です。なので、
- RK4はパラメータ設定だけなのでヘッダの中に書くので良いと思っている
- RKFはパラメータ設定と（少し複雑な）数式両方持っているので迷っている
- RKやembedded_RKは（少し複雑な）数式だけなので、分割するのが良いとおもている

という形になっているのだと思います。この辺りを他の人と擦り合わせて、`S2Eではどこでファイル分割するか`の方針を決める必要がありますね。

> 「実装ではなく実装のテンプレート」

の部分がいまいち僕が理解できていない部分な気がしています。  
今回のテンプレートの使い方では、状態量の要素数が変わる部分のみをtemplateで吸収していてそれ以外はどんな値でも変わらないので、「実装」と思われる部分がここに書かれているのが僕の認識です。  
これを継承したものは、パラメータ設定だけして、この実装部分をオーバーライドしたりはしません。  
なので、`実装のテンプレート`というのがわからないという感じです。


ただ、ここが折り合わなくても、
- 1ファイルでまとめれるものはまとめる
- 長くなったら`.cpp`や`_hoge.hpp`で複数に分ける

というのは必要なので、後は


- どんな基準でファイルを分けるのか
- ヘッダを二つに分ける場合は片方にはどんな名前を付けるのか

を決めるということになる気がしますがいかがでしょうか？

2023-06-19 13:37 UTC, seki-hiro reviewed
いくつか小さめのコメントつけました。

2023-06-19 13:47 UTC, seki-hiro reviewed
うまく送れていなかったので再送します。

2023-06-19 13:47 UTC, seki-hiro commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +  void ControlStepWidth(const double error_tolerance);
[IMO] 無次元化を想定しない場合、許容相対誤差の追加を見越して`absolute_error_tolerance`としてもいいのではないかと思います。

2023-06-19 13:47 UTC, seki-hiro commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
[IMO] 時刻の関数は単位をつけない方がいいと思いますが、いかがでしょうか？無次元化する場合も多いからです。

2023-06-19 13:47 UTC, seki-hiro commented on src/library/numerical_integration/numerical_integrator.hpp
> +    current_time_s_ = time_s;
他の場所と統一
```suggestion
    current_time_s_ = time_s;
    current_state_ = state;
    previous_state_ = state;
```

2023-06-19 13:47 UTC, seki-hiro commented on src/library/numerical_integration/test_runge_kutta.cpp
> +  libra::numerical_integration::RungeKutta4<1> linear_ode(0.1, ode);
他と統一
```suggestion
  double step_width_s = 0.1;
  libra::numerical_integration::ExampleLinearOde ode;
  libra::numerical_integration::RungeKutta4<1> linear_ode(step_width_s, ode);
```

2023-06-20 05:50 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
（ここだけでなく、runge_kuttaなどの中でも全て）単位をつけるかや、そもそも独立変数を時間に限定する必要も無いのでは　というのは迷ったところではあります。  
- 単位無しにする
- timeじゃなくて　independent_variable

にするなどいくつかパターンがあると思いますが、どう思いますか？

`time_s`にしているのは、短さ、わかりやすさ、大抵の場合はこれで良いから　みたいな理由で、コードを初めて読んだ人はこちらの方が読みやすいかなという感じで決めましたが、個人的には一般性高く`independent_variable`で無単位にしても良いかなとは思っています。

2023-06-20 07:19 UTC, 200km commented on src/library/numerical_integration/test_runge_kutta.cpp
> +  libra::numerical_integration::RungeKutta4<1> linear_ode(0.1, ode);
他と違って、step_widthを再利用していないので、この修正は必須ではないと思いますがどうでしょう？

2023-06-20 07:32 UTC, 200km commented on src/library/numerical_integration/ode_examples.hpp
> +    double inverse_square = 1.0 / pow(state[0] * state[0] + state[1] * state[1], 3.0 / 2.0);
exampleですし、本当に軌道運動のことを考えると半径が中心点対半径以下になるかのアサーションが良いと思いますが、一応入れました。

2023-06-20 08:05 UTC, seki-hiro commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
> （ここだけでなく、runge_kuttaなどの中でも全て）

はい、全体に対するコメントでした。

個人的な感覚ですが、単位なしの`time`がバランスいいと感じます。わかりやすさという意味では、`time_s`と変わらず、`time_s`ほど使われ方を限定しないからです。`independent_variable`とまでしてしまうと、逆にわかりにくいです。

2023-06-20 08:05 UTC, seki-hiro commented on src/library/numerical_integration/ode_examples.hpp
> +    double inverse_square = 1.0 / pow(state[0] * state[0] + state[1] * state[1], 3.0 / 2.0);
ありがとうございます。

2023-06-20 08:07 UTC, seki-hiro commented on src/library/numerical_integration/test_runge_kutta.cpp
> +  libra::numerical_integration::RungeKutta4<1> linear_ode(0.1, ode);
最初読んだ時にこの0.1はなんだろうとなったのでコメントしましたが、確かに必須ではないです。

2023-06-20 08:49 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
軌道などで`theta`を使う事があるからなどを気にしているのかなと思いましたが、そういうわけでは無いですかね。timeだけにするのは、中途半端かなと思っています.`time`と書かれていると無意識的に秒単位だろうと思い込んだりなど。。。  
難しいので他の人の意見も聞きましょうか。

2023-06-20 09:10 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +  void ControlStepWidth(const double error_tolerance);
Matlab側の細かな実装は分かりませんが、この許容誤差はembedded RK法での典型的なstepサイズ制御で使うものになります。基本は絶対誤差ですが、状態量が無次元化されていて1に近い値なら扱いとしてはMatlabの相対誤差に近くなります。ただ、この関数の中では誤差の概念は一つだけなので、そこをあえて「絶対誤差」と書く必要はないかなとは思います。  
強いていうなら、doxygenコメントをもう少しわかりやすくしたいという感じでしょうか。今は数式見てもらう想定ですが、それだと不親切なのかもしれません。

Matlabのような、絶対誤差と相対誤差をどちらも考えるstepサイズ制御を実装する場合は、この関数とは別に新たな関数が作られることになると思います。（それがユーザー側でできるように、`GetLocalTruncationError`関数を提供しています。）  
新たな関数が作られた時にはその関数の引数や内部ローカル変数名として、絶対か相対かを明確に分けるのは大切だとは思いますが、その時にはこの関数は特に影響を受けないかなと思っています。

あとは消極的な意見ですが、関数の引数名はIFに影響なくパッチで変えれるので、どうしてもabsoluteにしないと混乱するとなった時に変更でも良いかなと思ってはいます。

2023-06-20 09:13 UTC, 200km commented on src/library/numerical_integration/test_runge_kutta.cpp
> +  libra::numerical_integration::RungeKutta4<1> linear_ode(0.1, ode);
これはテストコードの中でも単純なconstructorの試験なので、入れる数値に特に意味などはないというのもあります。  
このままで進めたいと思います。

2023-06-20 20:31 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
@suzuki-toshihir0 こちら、鈴木くんはどう思いますか？

2023-06-21 04:37 UTC, seki-hiro commented on src/library/numerical_integration/embedded_runge_kutta.hpp
> +  void ControlStepWidth(const double error_tolerance);
わかりました。embedded RK法で典型的に使われているものということで、問題なさそうです。ユーザー側での使われ方をイメージできてない中でコメントしてしまっていましたが、ここはこのままで良いと思います。

2023-06-21 04:40 UTC, seki-hiro commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
thetaなどまで拡張しようというわけではありませんでした。単位がない方がいいという気持ちのみです。
有次元・無次元どちらのユースケースもあると思うので、他の方の意見ももらえると嬉しいです。

2023-06-21 04:40 UTC, seki-hiro commented on src/library/numerical_integration/test_runge_kutta.cpp
> +  libra::numerical_integration::RungeKutta4<1> linear_ode(0.1, ode);
わかりました

2023-06-21 05:54 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
- 'independent_variables': 時間に限らずなんでも使える
- 'time': 時間で無次元化したものも使える
- 'time_s': 単位あり時間限定

のどれが良いかというのと、＋S2E全体は単位あり時間で回っている　とかも考慮の余地はあるかもですね。S2Eで無次元化時間使う場面がどれくらいあるのかなども考えても良いのかもしれません。

2023-06-21 06:46 UTC, suzuki-toshihir0 commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
個人的にはODEの抽象クラスの中で使う純粋仮想関数なのであれば `independent_variable` まで抽象化してもよいと思います．
ここの部分であえて時間変数の微分に用途を制限しなくてもよいのでは？と考えています．

2023-06-21 08:38 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
多数決的には`independent_variable`になりそうな感じですが、どうですかね？まあ長すぎるのが微妙なんですよね。いい感じの短い単語があればいいんですが。  

この関数に関してはこの引数名を変えても継承側で別の名前にすれば良いだけですね。  

いまは全体の話をしているので、影響があるのは、
- `step_size_s`を`step_size`にする
- `NumericalIntegrator`の`current_time_s`を`current_independent_variable`にする

とかですね。

それで良さそうな気はしますが、お二人はどうでしょう？

2023-06-21 08:59 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
@seki-hiro @suzuki-toshihir0 こちらの件もなかなか議論が進まないので、お二人からもご意見いただきたいです。

2023-06-22 06:29 UTC, seki-hiro commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
はい、いいと思います。

2023-06-22 06:34 UTC, suzuki-toshihir0 commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
「独立変数」に対応する短い単語，どうも無さそうですね．．．`explanatory variable` も `predictor` もわかりにくいですし．具体的な実装側で変数名を変えて使うのでよいと思っています．

> - step_size_sをstep_sizeにする
> - NumericalIntegratorのcurrent_time_sをcurrent_independent_variableにする

については，私もそれで良いと思います．

2023-06-22 07:21 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
ありがとうございます。では、その方向で修正してみます。

2023-06-27 07:34 UTC, 200km commented on src/library/numerical_integration/interface_ode.hpp
> +  virtual Vector<N> DerivativeFunction(const double time_s, const Vector<N>& state) const = 0;
done

2023-06-27 21:27 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
@suzuki-toshihir0 コメントありがとうございます。
`ファイル分割の基準`については、これまでの流れから下記で問題なさそうなので、そのようにしたいと思います。
```
RK4はパラメータ設定だけなのでヘッダの中に書くので良い
RKFはパラメータ設定と（少し複雑な）数式両方持っているので迷うが、分ける方向で行く
RKやembedded_RKは（少し複雑な）数式だけなので、分割するのが良い
```

`分割した時に、もう一方も　.hppだった時のファイル名`についてですが、現状のS2Eでは`hoge_template_functions`となっています。これは、`分割した時に、もう一方も（.cppではなく）　.hpp`というのが今のところ、templateを使った時にしか発生しないので、それに引きづられているところはあります。

それらも含めて、全て`hoge_implementation.hpp`に統一するのもありかなとは思います。この部分以外を修正するのは別issueで扱いたいと思います。

@sksat この方向で良いでしょうか？

2023-06-28 00:40 UTC, suzuki-toshihir0 commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
はい，私としては `hoge_implementation.hpp` がよいのかなと思っています．

> この部分以外を修正するのは別issueで扱いたいと思います。

こちらも承知しました．

2023-06-28 04:27 UTC, sksat commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
はい．良いと思います > `hoge_implementation.hpp`

2023-06-28 05:21 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
ありがとうございます！

2023-06-28 07:20 UTC, 200km commented on src/library/numerical_integration/embedded_runge_kutta_template.hpp
I modified the codes reflecting the discussion of this thread.

2023-06-28 11:48 UTC, suzuki-toshihir0 approved these changes
私からは問題ないと思います！

2023-06-30 07:11 UTC, sksat approved these changes
問題なさそうです

2023-06-30 07:59 UTC, merged