[WIP] Add C2A command sender for accelerated SILS test
ut-issl/s2e-core pull request #485
Opened 2023-09-01 13:34 UTC by 200km

## Overview
Add C2A command sender for accelerated SILS test

## Issue
- #477 

## Details
I implemented C2A command sender component for accelerated SILS test.  
Users can use `WINGS's ops file` to define the commands they want to send.

##  Validation results
TBW

## Scope of influence
Minor update

## Supplement
NA

## Note
NA

2023-09-01 23:21 UTC, conjikidow commented
Thank you for the prompt implementation. I was able to confirm its operation in my environment.

However, there is another frequently used command, "let," besides "check_value" (as shown in the example below), and it is not supported, which leads to a runtime error.

```
let mode_id = 2
AOBC_RT.Cmd_MM_START_TRANSITION {mode_id}
```

Since this feature is frequently used in actual command files, it would be desirable to have this functionality for the use of validation.
This area is, however, dependent on WINGS syntax, and it highlights the difficulty of trying to implement something in S2E that is originally a part of WINGS' functionality. Sending command in S2E is, after all, rather simplistic, so it might be necessary to accept some limitations.

2023-09-02 05:30 UTC, 200km commented
このPRではletコマンドをサポートする予定はありません。今の段階でも多くの試験が高速SILSでできるようになるはずなので、細かな便利機能の追加を考えるより、まずは基本機能を追加することを優先したいと考えています。追加便利機能は、その後必要に応じて追加していけば良いと思います。（追加したいと思う人が追加してくれると助かりますので、issue立ててアサインしますね）. 

errorを出さずに無視して進めるように修正しようとは思います。

2023-09-02 08:29 UTC, 200km commented
`let`や引数に`{}`があってもエラーにならないように修正しました。

2023-09-04 04:35 UTC, conjikidow commented
わかりました，ありがとうございます。

2023-09-04 04:36 UTC, conjikidow approved these changes
`let` でエラーが出ないことも確認しました，ありがとうございます。

2023-09-04 09:34 UTC, sksat requested changes
これは意味的にだいぶ巨大な変更ですね......

なんだかんだであんまり明示できていなかったのですが，C2A と S2E は基本的にできるだけ疎結合にしたいと思っていて，S2E の `ObcWithC2a` 以外の部分で C2A の機能が用いられることは考えていませんでした．また，この部分ですら `TMGR_count_up_master_clock()` のような C2A 内部の関数を直接呼んでいることはよくないと考えており，これをさらにラップした `C2A_core_tick()` のような関数を用意して，S2E などのランタイムにはそれを呼んでもらうように変えたい，といった計画をしています．

そのため，使う C2A の機能を増やすのであればそれは慎重に考えたいです．
それでいうと，`ENDIAN_memcpy()` などは必ずしも必要ではない（別に SILS-S2E はビッグエンディアンな環境でビルドすることはなさそう）ですし，あまり使ってほしくないですね......

今回の PR の場合`CCP_register_rtc()`, `CCP_register_tlc()` などは本質的に必要になるので仕方ないと思うのですが，これはどうにかして明示したいですね．

2023-09-04 09:40 UTC, sksat commented
必ずしも ops ファイルの全機能をサポートするわけではない（しようと思っても現状では実装が仕様と化しているので厳しい）と思うので，WINGS の ops ファイルが使える，というような表現は避けて，あくまでサブセットであると明示した方がよいと思います

2023-09-04 11:05 UTC, 200km commented
> C2A と S2E は基本的にできるだけ疎結合にしたい

大きな流れとしてそうしていきたいのは、これまでの議論から察していますし、私も同意です。  
また、今回の機能の実現方法として今のS2E-C2A-WINGS SILS形態でWINGS側が高速で動くように修正するなど、C2AとS2Eの結合をこれ以上高めない方法などもあるとは思っています。
ただ、それらの実装がなかなか進まないなか、S2E-AOBC関連のユーザーが増えてきたので「高速SILSでコマンドを送る」機能の必要性が高まっています。この要望にクイックに応えるには、他の実装を待つのではなくS2E側で実装できる今回のような形が良いと思っています。

将来的にC2AとS2Eの結合が解けるようなことが進んだ場合には、この機能は無くしてしまって良いとは思います。

> ENDIAN_memcpy

こちらは、使わない方向で考えてみます。

> 明示したい

言葉がよくわかっておらず申し訳ないですが、どのようなことをすれば`明示した`ということになるのでしょうか？. 
コード中のコメントなどで記述するという感じなのか、s2e-document的なものに書くべきなのかなど教えてください. 
例えばOPSファイルについてはサンプルにサポートしていない機能などは書いていますが、別の場所にも分かりやすく書くべきということでしょうか？

2023-09-04 17:54 UTC, 200km commented
C2AのENDIAN_memcpyではなく、S2Eが持っていたendian_memcpyを使うようにしました。

2023-09-07 05:06 UTC, sksat commented
高速で SILS を回しつつコマンドを送りたい，という要求自体は AE 側でも上がっていて，その重要性についてはとても同意します（pytest を高速化したい，など）．
その上で，直近でこの要望にクイックに応えるには S2E 側で今回のような実装をする，ということもとてもアリだと思っています．
ただし，S2E <-> C2A の結合を密にしてしまう，ops ファイル・TlmCmdDB の実装（のサブセット）が増えてしまうといった点から，この機能をこの実装方針のまま維持しようとすると大きな負債となってしまうのではないかということを危惧していました．そのため，
> 将来的にC2AとS2Eの結合が解けるようなことが進んだ場合には、この機能は無くしてしまって良いとは思います。

ということであれば，その懸念はある程度解消できるかな，と思います．
また，他の実装，については [Gaia](https://github.com/arkedge/gaia) が OSS 化されたこともあり，S2E-C2A-Gaia での SILS が可能になれば比較的すぐ実装可能なのではないか，とも考えています（Gaia では1秒おきの更新ではなくストリーム接続なので，高速な動作に耐えられます）．

ありがとうございます． > `ENDIAN_memcpy` を使わないように実装

すみません言葉不足でした．これはどちらかというと C2A（-core）側の話で，C2A（-core） が S2E を含む外部のソフトウェア（ランタイム/シミュレータ）に対して公開しなければならない関数（単に仕組み的なところでは include してしまえばなんでも使えてしまいますが，それでは疎結合にできないので使っていい関数をホワイトリスト方式で管理したい）をドキュメントなどで明らかにして，そのインターフェースを変更する場合は major update としていきたい，という意図でした．とはいえ S2E 側でもドキュメント（ユーザに対するもの，というよりはコーディングルールの類ですかね）で C2A のこれは使ってよい，というようなことは明示しておきたいかもですね． > 明示したい

2023-09-07 12:16 UTC, 200km commented
@sksat ありがとうございます。
> [Gaia](https://github.com/arkedge/gaia) が OSS 化されたこともあり，S2E-C2A-Gaia での SILS が可能になれば比較的すぐ実装可能

これは、ありがたい情報ですね。私自身はGaiaはまだ使ったことがない状況ですので、まずはリアルタイムのS2E-C2A-Gaia SILS環境を試してみたいと思います。もし手順書などすでにあれば教えてもらえると嬉しいです。

> 明示する

説明理解しました。外部に対するAPIをきちんと定義するというようなことにも関係しますかね。（S2Eもsemver使っているのにAPI定義していないのでいつかちゃんとしなきゃなとは思っています。）

とりあえずこのPRではどうすれば良いでしょうか？

2023-09-11 09:48 UTC, 200km commented
@sksat ありがとうございます。コメントつけましたのでレビューお願いします。

2023-10-05 17:09 UTC, sksat requested changes

2023-10-05 17:09 UTC, sksat commented on src/components/real/communication/wings_command_sender_to_c2a.cpp
> +#include "src_core/TlmCmd/common_cmd_packet_util.h"
c2a-core v4 ではディレクトリ名が変わっています
```suggestion
#include "src_core/tlm_cmd/common_cmd_packet_util.h"
```

2023-10-05 17:12 UTC, sksat commented
あと，https://github.com/ut-issl/s2e-core/pull/485/commits/9c9369c6dcf55a55106c74f4de6985c1f249eec1 を見て思ったんですが，`C2A_CORE_VER_MINOR` >= 9` みたいなバージョンチェックは入れてもいいかもです．

2023-10-05 17:56 UTC, 200km commented on src/components/real/communication/wings_command_sender_to_c2a.cpp
> +#include "src_core/TlmCmd/common_cmd_packet_util.h"
https://github.com/arkedge/c2a-core/tree/v4.0.0-beta.0

この修正を行なった時には、こちらしかなかったので、TlmCmdでしたが、レビューを待っている間（先週）に新しくリリースbeta.1がされたようですね。

2023-10-05 18:03 UTC, 200km commented
> C2A_CORE_VER_MINOR >= 9` みたいなバージョンチェック

[9c9369](https://github.com/ut-issl/s2e-core/commit/9c9369c6dcf55a55106c74f4de6985c1f249eec1)の修正は、version 9以上でしか使えなくしたというわけではなく、「Cmd_　prefiｘがついているかのversionは関係なく、Cmd_DB上のコマンド表記とOPSファイル内のコマンド表記が一致しておけば良い」という修正になります。  
C2Aが古く、Cmd_DB上でCmd_ prefixがついたものであれば、そのまま使えます。

2023-10-05 18:09 UTC, 200km commented on src/components/real/communication/wings_command_sender_to_c2a.cpp
> +#include "src_core/TlmCmd/common_cmd_packet_util.h"
よくみたら、beta.0はyankされてしまっているようですね。

2023-10-05 18:10 UTC, sksat commented on src/components/real/communication/wings_command_sender_to_c2a.cpp
> +#include "src_core/TlmCmd/common_cmd_packet_util.h"
そうです．そして `arkedge/c2a-core` v4.0.0-beta.0 の yank などもあってゴタゴタしていたのもあってお知らせが遅くなってしまっていました......

2023-10-05 18:12 UTC, sksat commented
なるほどです．勘違いしていました > `Cmd_` prefix

2023-10-05 18:24 UTC, sksat approved these changes

2023-10-05 18:26 UTC, merged