Modify physical constants management
ut-issl/s2e-core pull request #76
Opened 2022-04-05 18:02 UTC by 200km

## Overview
Modify physical constants management.

## Issue
- #7 

## Details
Physical constants are defined in `Environment/Global/physical_constants.hpp`.   
All codes refer to the values from there.  
Angular conversion constants are also defined in `Library/math/constant.hpp`.

##  Validation results
I confirmed the output log file is similar between before and after this modification.

## Scope of influence
large

## Supplement
Some codes from outside still have several constant values, but I didn't focus on them in this PR. 

## Note
- NA

2022-04-05 23:43 UTC, seki-hiro approved these changes

2022-04-06 07:09 UTC, sksat requested changes

2022-04-06 07:09 UTC, sksat commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
`libra`は由来はよくわからないものの，行列系のクラスなどが入っている名前空間だったので，数学系の定数(#52)については[合わせました](https://github.com/ut-issl/s2e-core/pull/52#issuecomment-1047353883)が，物理定数などは文脈が異なるので合わせる必要は無いのではないかなと思います．

また，`libra::numbers`はC++20の`std::numbers`と被っているため後で移行しやすいようにしたというかんじなので，こちらは明確に要らないと思います．

2022-04-06 07:09 UTC, sksat commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
まあ`libra`はナシでもないかもしれないですが(どうだろ)，せっかく名前空間という仕組みを使っているのに名前から文脈が分からないのはかなり片手落ちなので，主にその意味でrequest changesとします．

2022-04-06 07:48 UTC, 200km commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
たしかに、そこは少し迷いました。  
`libra::numbers::`じゃなくどんな命名が良さそうですかね。安直に`physical_const::`とかですかね。

2022-04-06 07:52 UTC, sksat commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
`src/Environment`ですし`environment::physics`みたいなかんじがよいかも．名前空間で定数であることを明示する必要はあんまり無いと思います．

2022-04-06 07:59 UTC, 200km commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
確かに`environment`つけるのは良さそうです。  
これは完全に個人的な感覚の話なんですが、`physics`って強い(対象が広い)単語過ぎて使いづらく、`physical_constant`にすると少し柔らかくなるかなとは思ってしまいました。  
天体関連の定数はphysicsだとイマイチな気もするので、`environment::astronomy`とかで分けて、光速とかにだけphysics使うのはありかもですね。

2022-04-06 08:01 UTC, sksat commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
語義が広すぎるのは確かに．`astronomy`とかも分けるのはかなりアリですね．

2022-04-06 12:45 UTC, 200km commented on src/Environment/Global/PhysicalConstants.hpp
> +inline namespace numbers {
I changed the namespace as `environment::physics` and `environment::astronomy`.

2022-04-07 10:07 UTC, sksat approved these changes
LGTM

2022-04-07 10:09 UTC, merged