Modify management of initialize files
ut-issl/s2e-core pull request #91
Opened 2022-04-19 11:38 UTC by 200km

## Overview
Modify management of initialize files

## Issue
#9 

## Details
Write in detail.

##  Validation results
NA

## Scope of influence
?

## Supplement
NA

## Note
NA

2022-04-19 14:46 UTC, sksat reviewed
こんなかんじでよさそうです(作業中っぽいのでapproveはしないでおきます)．
あと，Draft PRだとSlackに通知が飛ばなかったりするので，作業中の間はPR titleの頭に`WIP: `とか付けて普通のPR，でいいかもです．

2022-04-19 15:23 UTC, 200km commented
ありがとうございます。  
Draft PRの件承知しました。

2022-04-21 00:10 UTC, seki-hiro approved these changes

2022-04-21 04:47 UTC, 200km commented
一応 @sksat さんからapproveもしくはコメントを貰ってからマージしようと思います。

2022-04-21 05:40 UTC, sksat requested changes

2022-04-21 05:40 UTC, sksat commented on src/Interface/LogOutput/InitLog.hpp
> +#pragma onece
```suggestion
#pragma once
```

2022-04-21 05:43 UTC, sksat commented on src/Interface/LogOutput/InitLog.hpp
> +#pragma onece
自明なtypoなんでcommitしちゃいます

2022-04-21 05:50 UTC, sksat approved these changes

2022-04-21 05:51 UTC, suzuki-toshihir0 approved these changes

2022-04-21 09:39 UTC, merged